apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
{{- with .Values.secret.data }}
data:
{{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
