secret:
  enabled: false        # Helm will NOT create a Secret unless set to true
  name: ""              # Secret name must be provided when enabled
  data: {}              # Key-value pairs will be base64 encoded automatically
